---
dist: bionic

language: python
python:
  - 3.6

env:
  global:
    - VAGRANT_VER: 2.2.9
  matrix:
    - MOLECULE_DISTRO_BOX: enr0s/ubuntu-focal

install:
  - sudo add-apt-repository universe && sudo apt update
  - wget https://releases.hashicorp.com/vagrant/$VAGRANT_VER/vagrant_"$VAGRANT_VER"_x86_64.deb
  - sudo dpkg -i vagrant_"$VAGRANT_VER"_x86_64.deb
  - sudo apt install qemu-kvm qemu-utils libvirt-bin libvirt0 libvirt-dev
  - vagrant plugin install vagrant-libvirt
  - pip install molecule molecule-vagrant docker python-vagrant paramiko
  - sudo chmod o+rwx /var/run/libvirt/libvirt-sock

script:
  - ansible --version
  - molecule --version
  - printf '[defaults]\nroles_path=../' >ansible.cfg
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
