---
dependency:
  name: galaxy
lint: |
  yamllint .
  ansible-lint
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: master
    box: ${MOLECULE_DISTRO_BOX:-""}
    memory: 1024
    cpus: 2
    provision: yes
    groups:
      - masters
  - name: worker
    box: ${MOLECULE_DISTRO_BOX:-""}
    memory: 1024
    cpus: 2
    provision: yes
    groups:
      - workers
provisioner:
  name: ansible
  env:
    ANSIBLE_FORCE_COLOR: 'true'
  options:
    vvv: false
  inventory:
    group_vars:
      all:
        ansible_ssh_user: vagrant
        ansible_ssh_pass: vagrant
        run_not_in_container: true
        kubernetes_kubelet_extra_args: "--fail-swap-on=false"
        kubernetes_kubeadm_init_extra_opts: "--ignore-preflight-errors all"
        kubernetes_join_command_extra_opts: "--ignore-preflight-errors all"
verifier:
  name: ansible
